// Code generated by sqlc. DO NOT EDIT.

package codegen

import (
	"database/sql"
	"time"
)

type Post struct {
	ID        string         `json:"id"`
	User      string         `json:"user"`
	Title     string         `json:"title"`
	Content   sql.NullString `json:"content"`
	Updated   bool           `json:"updated"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Upvote struct {
	Post      string    `json:"post"`
	User      string    `json:"user"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}
