// Code generated by sqlc. DO NOT EDIT.

package codegen

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int32     `json:"id"`
	PostID    int32     `json:"post_id"`
	UserID    int32     `json:"user_id"`
	Content   string    `json:"content"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Post struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	Title     string         `json:"title"`
	Content   sql.NullString `json:"content"`
	UpdatedAt time.Time      `json:"updated_at"`
	CreatedAt time.Time      `json:"created_at"`
}

type Upvote struct {
	ID        int32     `json:"id"`
	PostID    int32     `json:"post_id"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}
