package persistence

import (
	"database/sql"

	_ "github.com/lib/pq"
	"github.com/spf13/viper"
	"polygon.am/core/pkg/persistence/codegen"
)

// This exported variable contains all the queries generated
// by sqlc for usage with PostgreSQL.
var Queries *codegen.Queries

// This function will attempt to open a connection to the specified
// PostgreSQL URL and initialize the queries generated by sqlc.
func Connect() error {
	dsn := viper.GetString("polygon.persistence.postgres")
	conn, err := sql.Open("postgres", dsn)
	if err != nil {
		defer conn.Close()
		return err
	}

	Queries = codegen.New(conn)
	return nil
}
